apiVersion: v1
kind: Service
metadata:
  name: minimum-routing-cost-path-service
spec:
  selector:
    app: minimum-routing-cost-path
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer